{% set name = "pdfcombine" %}
{% set version = "1.1.1" %}
{% set sha256 = "395408a3dc9c3db2b5c200b8722a13a60898c861633b99e6e250186adffd1370" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/pdfcombine/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pdfcombine = pdfcombine.cli.pdfcombine:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - docopt
    - click
    - pyyaml
    - ghostscript

test:
  imports:
    - pdfcombine
  commands:
    - pdfcombine --help

about:
  home: https://github.com/tdegeus/pdfcombine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Combine PDF files with Ghostscript'
  description: 'Combine PDF files with Ghostscript'
  doc_url: https://github.com/tdegeus/pdfcombine
  dev_url: https://github.com/tdegeus/pdfcombine

extra:
  recipe-maintainers:
    - tdegeus
