{% set version = "1.1.5" %}

package:
  name: pdfcombine
  version: {{ version }}

source:
  url: https://github.com/tdegeus/pdfcombine/archive/v{{ version }}.tar.gz
  sha256: 773e50a00fb91dc3a2dd71164bb8a8b24b2168a9aad4c5f1072f2669a904104f

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pdfcombine = pdfcombine.cli.pdfcombine:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - click >=4.0
    - docopt >=0.6.2
    - ghostscript
    - numpy
    - python >=3.6
    - pyyaml >=1.0

test:
  requires:
    - pip
  imports:
    - pdfcombine
  commands:
    - pip check
    - python -c "import pdfcombine; assert pdfcombine.version == '{{ version }}'"
    - pdfcombine --version | grep {{ version }}

about:
  home: https://github.com/tdegeus/pdfcombine
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Combine PDF files with Ghostscript'
  description: 'Combine PDF files with Ghostscript'
  doc_url: https://github.com/tdegeus/pdfcombine
  dev_url: https://github.com/tdegeus/pdfcombine

extra:
  recipe-maintainers:
    - tdegeus
